databases:
  - name: dental_clinic_db
    plan: free
    databaseName: dental_clinic
    user: dental_clinic

services:
  - type: web
    plan: free
    name: kingjoy-dental-clinic
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'gunicorn dental_clinic_project.wsgi:application'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dental_clinic_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: 'kingjoy-dental-clinic.onrender.com'
      - key: EMAIL_HOST_USER
        value: '987f0e001@smtp-brevo.com'
      - key: EMAIL_HOST_PASSWORD
        generateValue: false
      - key: DEFAULT_FROM_EMAIL
        value: 'noreply@kingjoydental.site'
      - key: DEFAULT_FROM_NAME
        value: 'KingJoy Dental Clinic'